"""Part 7.35.2 data for tools/sync-provenance.py. Executed into that tool's namespace by
tools/partlib.py; the tool holds the code, this file holds what is true of the Part."""

CHANGED = {
    "rules-7.35.2-adopted-2026-06-23-published":
        "The adopted rule, published in the New Mexico Register on June 23, 2026 and in effect "
        "from that day: twenty-seven sections governing producer and laboratory permits, "
        "premises, allowed products, traceability, the five required tests and their action "
        "levels, packaging and the product information document, wastage, transportation with a "
        "chain of custody, monitoring, and discipline. It supersedes the text proposed on March 24 "
        "and heard on April 24, 2026. Proposed amendments to three of its sections were "
        "published August 25, 2026 and go to a hearing on October 2; until adopted, the text here "
        "stands unamended.",
}

# Per-page revision entries, newest first.
REVISIONS = {
    "index": [
        ("September 7, 2026", "Created as the front page of the Part: the plaque, the portals by role, the status surfaces written by tools/sync-status.py, what the August 25 amendments would change, and the page directory."),
    ],
    "rule": [
        ("September 7, 2026", "Created, generated from the Register extraction by tools/build-rule-page.py: all twenty-seven sections verbatim, cited to the PDF page, with the three sections the August 25 amendments would change annotated at the section."),
    ],
    "producers": [
        ("September 7, 2026", "A section at the top, Before you apply: what the rule says an applicant has in hand, cited item by item, with what the rule does not state about the application itself."),
        ("September 7, 2026", "Created: what the adopted rule requires of a producer, in the order a producer meets it, from the permit application through discipline, each requirement cited to its subsection and page, and what the August 25 amendments would change."),
    ],
    "laboratories": [
        ("September 7, 2026", "A section at the top, Before you apply: the records and the credential a laboratory applicant has in hand, cited item by item, with what the rule does not state about the application itself."),
        ("September 7, 2026", "Created: what the adopted rule requires of a psilocybin testing laboratory, from the accreditation the permit rests on through the five required tests, the additional services the rule allows, reporting, and discipline, each cited to its subsection and page."),
    ],
    "record": [
        ("September 7, 2026", "Created: the dated chain from the March 24 notice through the October 2 hearing, the register, and the gaps, generated by tools/sync-record.py. Records of the Propagation Committee's meetings are not held and are registered as absent."),
    ],
    "comment": [
        ("September 7, 2026", "Created: the October 2 hearing's mechanics from the notice, the three amendments at issue, and the input form."),
    ],
}
