#!/usr/bin/env python3
"""Keep the provenance block identical and current across every page in docs/.

Two things a reader needs and the site did not have:

1. The document chain. Four successive documents govern this subject. Each
   supersedes the one before it. A reader looking at a number on any page
   should be able to walk back and see where it came from and what changed at
   each step, without that history sprawling across the page.

   The chain is stated once, in the register at record.html#documents, whose
   data lives in tools/sync-record.py and is read from there by this script.
   The register holds each document's identity, date, status, and download; the
   block at the foot of a page names the current document, says what it changed,
   and links the register. It used to restate all four documents with their own
   download links, which put the same description of the same document on eight
   pages in different words, and that is the one document-link duplication on
   the site that serves no citation.

2. A per-page revision log. What was changed on this page, and when. Only
   index.html had one, buried in its footer.

Both live in a single collapsed <details> block at the foot of every page:
zipped up by default, opened when a reader wants it.

CHAIN is identical on every page. REVISIONS is per page, newest first.

Every content page carries the block. The seven pages restored from the
pre-redesign site hold it before their sitefoot, with the block's styles
injected into each page's own stylesheet; the seven pages built in the July
27 redesign idiom hold it at the end of main, with the styles in the shared
style.css. Redirect stubs are retired addresses, not destinations, and
carry no block.

Usage:
    python3 tools/sync-provenance.py           # write into every page
    python3 tools/sync-provenance.py --check   # exit 1 if any page is stale
"""
import glob
import importlib.util
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")

# The document chain lives in the register, in tools/sync-record.py, which is
# where record.html reads it from as well. This block used to carry its own copy
# of every document's date, name, and file, which is two homes for one fact and
# the drift pattern the register exists to end. What stays here is the one thing
# the register does not hold: what the current document changed, which is the
# chain narrative rather than the document's identity.
_spec = importlib.util.spec_from_file_location(
    "syncrecord", os.path.join(ROOT, "tools", "sync-record.py"))
syncrecord = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(syncrecord)

CHAIN = [d for d in syncrecord.DOCUMENTS if d.get("chain")]

CHANGED = {
    "rules-draft-2026-08-25-published":
        "The revised proposed rule, published August 25 with the notice fixing the October 2 "
        "hearing, superseding the set-aside July 23 text. Raised the practitioner and "
        "facilitator therapy module from 30 didactic hours to 65, at least one third in "
        "person, and the simulated patient requirement from 5 hours to 10. Added eleven "
        "curriculum topics without per-area hour minimums, a case-presentation evaluation "
        "inside the unchanged 100 and 120 practicum hours, a low-risk requirement on the "
        "first 20 administration-day hours, and a didactic waiver. Kept the role names "
        "certifying clinician and practitioner, defining them in amendments to 7.35.2.7 "
        "published the same day.",
    "rules-draft-2026-07-23-published":
        "The department's proposed rule as published July 23, set aside with its August 28 "
        "hearing and standing as the last published text; revised rules are forthcoming, "
        "with the hearing anticipated for early October. "
        "First version with final section numbering, 7.35.3.1 through .28. Raised the shared "
        "didactic module from 25 hours to 30 and added three curriculum topics. Carried the 100 "
        "and 120 practicum hours forward unchanged, six days after the board voted 7-0 to send "
        "those hours back to committee. Wrote both waiver dates as December 31, 2027. Added a "
        "rule that the practicum may not begin before half the didactic and all simulated "
        "patient hours are complete.",
}

# Per-page revision entries, newest first. Keep each one specific: what changed,
# not that something changed.


REVISIONS = {
    # The seven redesign-idiom pages were created July 27, 2026; their logs
    # run from that date, seeded from the repository history. The revisions
    # of their pre-redesign predecessors remain in that history.
    "index": [
        ("August 26, 2026", "The front page flipped to the August 25 publication: the plaque, the portals, and the what-changed column carry the revised proposed rule, the amendments to 7.35.2 NMAC, and the October 2 hearing fixed by notice, with the status surfaces regenerated by tools/sync-status.py."),
        ("August 24, 2026", "An accuracy pass corrected the front page: the July 23 column reports the August 28 hearing as set aside rather than as what the hearing runs on, the eligibility portal counts thirty-seven starting points, and the October 2 hearing moved from the Scheduled list to its own Anticipated label."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "The full content pass to the current state: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules. The plaque, the procession, the status items, and the Scheduled column now say so, with the September 4 and September 11 meetings and the anticipated early-October hearing listed."),
        ("August 21, 2026", "The plaque, the comment portal, and the status surfaces now carry the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date. The Scheduled column lists the August 25 publication, the September 4 committee meeting, and the anticipated hearing."),
        ("August 13, 2026", "The three Where things stand lines and the Scheduled dates are now written by tools/sync-status.py, which holds each status item's state, date, and one-line summary once and writes every surface that shows them, so a date that moves or an item that settles is corrected in one file. The tool emits the text the page already carried, and nothing a reader sees changed."),
        ("July 31, 2026", "The open item on the hours now states what each submitted figure replaces: 80 classroom hours in place of 40, a staged practicum of 60 or 70 hours by role in place of 100 or 120, and 20 hours of case presentation and consultation in place of 10 hours of mentoring."),
        ("July 28, 2026", "A seventh portal serves the reader who wants to comment on the rule, and the front page now carries the one-sentence patient signpost stating that this site covers provider training while patient access is set by the Act. The DEFECT line now states how the rule page's five defect notes relate to the three provisions flagged on What a practicum change touches, because the two counts are not a subset of each other and a reader who met both had no way to reconcile them. The page name is now the same in the title, the heading, and the menu: where things stand."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy. The portals now lead with the questions a first-time visitor brings, the routes page first."),
        ("July 27, 2026", "Created in the July 27 redesign as the site's front page: the dated plaque, the portals by role, Where things stand, the procession, and what changed on July 23. Later the same day the full page directory was added at #directory, and the committee recommendation was recorded as submitted, with its figures stated in the open item."),
    ],
    "rule": [
        ("August 26, 2026", "Two definitions notes entered: the clinician definition does not cover the certifying clinician, whose subtype it anchors, because it reaches only the three-session medical services; and the qualified-patient definition substitutes certifying clinician where the Medical Psilocybin Act's own definition says clinician, placing the statutory appropriateness judgment in the number-holding role."),
        ("August 26, 2026", "An open note entered at 7.35.3.11: the other-approved-location application requires proof of ownership or a signed statement from the property owner acknowledging program participation on the premises, so a renting patient needs the landlord's signature to be treated at home, with the landlord-approval and privacy question raised at the August 21 committee meeting noted."),
        ("August 26, 2026", "A definitions section entered between 7.35.3.7 and .8, generated from the amendments extraction: the twenty-five program-side definitions of the amended 7.35.2.7 verbatim in the amendment's own strike-and-add notation, each cited to its page, with notes on the contested certifying-clinician scope, the rewritten practitioner, the struck guide, and where the qualifying conditions bind the curriculum."),
        ("August 26, 2026", "Regenerated from the August 25 extraction by tools/build-rule-page.py, whose chrome was brought current so the generator runs again instead of being mirrored by hand: all twenty-eight sections of the revised text, the annotations rewritten for what changed, the four heading misprints corrected in the text and the one that persists noted at 7.35.3.25."),
        ("August 24, 2026", "Reframed as the last published text: the July 23 publication and its August 28 hearing were set aside, and the kicker and lede state the set-aside. The annotation notes at 7.35.3.18 and .19 now state the recommendation at its August 21 position, 80 didactic hours and a staged practicum of 102 or 114, in place of the July 27 figures; mirrored into tools/build-rule-page.py. The text is unchanged."),
        ("August 21, 2026", "The kicker now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date. Mirrored into tools/build-rule-page.py, which owns this page."),
        ("July 28, 2026", "The defect notes that name findings B1, B4, and B5 now link those findings on What a practicum change touches, so a named cross-reference no longer asks the reader to go search. The links were mirrored into the page by hand because tools/build-rule-page.py, which owns this page, still carries retired chrome; the generator now refuses to run until that is brought current, rather than silently replacing the shared menu and the visit counter. The page name is now the same in the title, the heading, and the menu: the published rule."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign, generated from the published extraction by tools/build-rule-page.py: all twenty-eight sections verbatim, with the state of each contested provision, the five defect notes, and the heading misprints noted at the provision they belong to. Citations open on hover, close on leave, and open the source in a new tab on click. The annotations moved into the generator the same day, so regeneration keeps them, and the submitted recommendation's figures entered the annotations with them."),
    ],
    "record": [
        ("August 26, 2026", "The register gained the enabling statute: Senate Bill 219, the Medical Psilocybin Act, as enacted in 2025, with a chain event at its effective date. The site had cited the Act throughout without holding it."),
        ("August 26, 2026", "The chain flipped to the August 25 publication: a filing event with the revised rule, the 7.35.2 amendments, and the hearing notice attached, the July 23 row restated as superseded, the October 2 hearing moved from Anticipated to Scheduled, and the hearing-notice gap closed."),
        ("August 24, 2026", "An accuracy pass corrected the page: the October 2 hearing event is labeled Anticipated rather than Scheduled, the update stamp carries the date of the latest revision, and the individual-certifications item of the July 23 entry cites 7.35.3.9 (E) and (F) rather than (A)."),
        ("August 24, 2026", "The chain re-based to the current state: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules. The August 14 board meeting entered the chain as a meeting event, with the set-aside on its record, a gap row for its unposted recording and the missing set-aside notice, and the September 11 board meeting scheduled."),
        ("August 21, 2026", "The August 21 committee meeting entered the chain as a meeting event: both hours proposals reviewed side by side, no vote taken, and the schedule restated, the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date. The hearing-notice gap now points at the anticipated October 2 hearing, and a gap row records that no recording or transcript of the August 21 meeting is held here yet."),
        ("July 28, 2026", "The page is now generated from one data structure: tools/sync-record.py holds the events, the document register, and the gaps register, and writes the marked regions of this page. Every meeting, publication, filing, and scheduled date is one event with a stable anchor in the form e-YYYY-MM-DD, carrying what happened, what changed as one state transition per line, and every document it produced, with an absence stated at the event and linked to its gaps row. A reference that does not resolve in both directions fails the checks."),
        ("July 28, 2026", "The July 16 End-of-Life Care committee meeting entered the gaps register, which UPDATING.md had listed all along and the register did not, and the gaps rows gained anchors so a page can cite an absence. The page name is now the same in the title, the heading, and the menu: meetings and filings."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign: the dated chain and the document register on one page. Later the same day the gaps register returned beside the held documents, the chain recovered the substance the pre-redesign history page carried, with the July 17 morning and afternoon sessions as separate entries, and the July 27 filing of the committee recommendation entered the chain with its figures."),
    ],
    "hours": [
        ("August 26, 2026", "The model re-based to the August 25 published position as the default: the module total 80, the practicum 100 or 120 with the case-presentation evaluation stated, mentoring 10, beside the recommendation's August 21 position; the role toggle reads Practitioner, and the source note quotes the revised text."),
        ("August 24, 2026", "An accuracy pass corrected the sourcing note, which described the model's two positions as both from August 21, and the off-preset label, which now reads matching neither position."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "The model re-based to two positions: the recommendation, at its August 21 position of 80 classroom hours and a staged practicum of 102 or 114 hours with nothing further required after it, as the default, and the last published text of July 23, since set aside, as what it replaced. Dr. Anne Metz's July 17 figures moved to the training-hours record, and the July 27 submission to the recommendation page's history."),
        ("August 21, 2026", "The kicker and the model's position note now state the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("August 13, 2026", "The kicker above the model is now written by tools/sync-status.py, which holds the status of the rulemaking once and writes every surface that shows it, so the line stating what is open and what was submitted is corrected in one file when it changes."),
        ("July 31, 2026", "The model now carries three named positions, each with its date and its own colour: the rule published July 23, the recommendation Dr. Anne Metz presented on July 17, and the recommendation the committee submitted on July 27. A strip above the sliders names the position on screen at all times, the buttons show which one is set, and moving a slider off all three says so rather than leaving the reader to guess. Every figure in the Metz position is quoted in the source note from her written recommendations, which are held in docs/documents; the committee position states that its figures are reported rather than checked, because that document is not in the public record."),
        ("July 28, 2026", "The third quantity was labelled Supervision and cited to 7.35.3.18 and .19 alone, while the published 10-hour figure it carries is the mentoring requirement; verified against the published PDF, it now names mentoring and consultation and cites 7.35.3.17 (A), p. 10. One line beneath the model links the two routing instruments, the routes and the license tables. The page name is now the same in the title, the heading, and the menu: the training hours."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign: the working model of the deferred quantities, with the three sliders, the role toggle, and the program-total and cost reads against the published position. The submitted recommendation's figures entered the model the same day."),
    ],
    "recommendation": [
        ("August 26, 2026", "The against-the-published-text rows deepened to quote level: each row carries the published text's exact words and its own anchor, so a single item can be linked from a message or a written comment."),
        ("August 26, 2026", "The comparison posture switched on: a section states what the August 25 text took, altered, and declined against the August 21 position, the status and evolution sections carry the outcome, and the roles state the published names beside the recommendation's proposed renames."),
        ("August 24, 2026", "An accuracy pass corrected the Licensed Provider description: the name is the recommendation's, used by the department's presenter at the August 21 meeting while the department's own side-by-side kept practitioner."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "Rebuilt as the recommendation, standing alone: the three roles, the by-role table, the pathway drawn as a diagram, the 80 didactic hours with the nine content-area minimums, the staged practicum table, the case presentation and consultation checkpoint, the emergency credentials, continuing education, records, and the 2027 transition, the recommendation's own Colorado comparison, and its history from July 17 through August 21. Nothing on the page is diffed against another text, because no proposed rule is currently published; what was said at the August 21 meeting, including the department's presentation there, stays on the record page. Sourced to the August 21 meeting, with the absence of its recording tracked in the gaps register."),
        ("August 21, 2026", "The THEN line now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("July 28, 2026", "The Case presentation and consultation row cited the published 10-hour figure to 7.35.3.19 (C), which carries the practitioner's separate 20 supervisory hours; the published counterpart of the recommended consultation requirement is the mentoring requirement, and the row now cites 7.35.3.17 (A), p. 10, verified against the published PDF. The page name is now the same in the title, the heading, and the menu: the committee recommendation."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign, and brought to the submission the same day: the summary of the recommended rules reached the department on July 27, and this page states its figures beside the published text, 80 didactic hours, a staged practicum of 60 or 70 hours by role, and 20 hours of case presentation and consultation on two cases, with the July 17 presentation kept as the basis. The document itself is not published on this site; every figure is stated here and named to its source."),
    ],
    "comment": [
        ("August 26, 2026", "A fourth at-issue item: the owner statement at 7.35.3.11 (B)(9), which requires a renting patient to obtain the landlord's signed acknowledgment of program participation on the premises before treatment at home, stated in one line linking the rule page note that holds it."),
        ("August 26, 2026", "The hearing mechanics entered from the notice: October 2, 9:00 AM, Harold Runnels Building auditorium, by video conference and telephone, written comment to the office of general counsel by the close of the hearing, comments published within three days; the at-issue items re-based to the August 25 text."),
        ("August 24, 2026", "An accuracy pass corrected the page: the hours item states the recommendation at its August 21 position, standing alone, and reports that the July 23 text raised the didactic module; the Amy Wong-Hope comment is attributed to the July 17 committee meeting; the update stamp carries August 24."),
        ("August 24, 2026", "Re-based to the current state: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules. The kicker, lede, and hearing section state the set-aside, the anticipated October 2 hearing, and the department's statement that comment continues from publication through the hearing."),
        ("August 21, 2026", "The kicker, the lede, and the hearing section now state the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date, and that the department said public comment continues after publication, through the hearing."),
        ("August 13, 2026", "This page now owns the input log. Form submissions and their published texts are published here, marked as received through the form, and public comment given at a meeting is linked in one line to the meeting record that holds it rather than pasted. One received comment had lived in full on both this page and the training-hours record."),
        ("July 28, 2026", "A what-is-at-issue section now precedes the form: the open hours and the submitted recommendation, the kept controlled-substance number requirement, and the five defect notes, each stated in one line linking the page that holds it. The page name is now the same in the title, the heading, and the menu: comment."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign: the hearing facts and the input form, with its consent checkbox and stated handling. The community input log returned below the form the same day, with both July 17 entries."),
    ],
    "training-hours-record": [
        ("August 26, 2026", "The role tiles, the published-hours section, the waiver table, the benchmark row, and the cost tiles carry the August 25 figures: the shared module at 65 didactic hours with 10 simulated, the practicum unchanged at 100 and 120 with the evaluation gate, the subsections relettered; the middle role reads practitioner with the recommendation's proposed rename noted."),
        ("August 24, 2026", "An accuracy pass corrected the page: the July 9 quotations carry the transcript's exact words with every elision marked, the discretionary waiver is named by its published position at 7.35.3.19 (F), the reciprocity-waiver cite moved to page 5, the Amy Wong-Hope comment is attributed to the July 17 committee meeting, and the renumbered section cross-references were repaired."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "The August 21 committee record entered as section 2, with the later sections renumbered: what the meeting settled, what it left open, and the schedule as restated. The strip and the section state that the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules."),
        ("August 21, 2026", "The status strip now records the August 21 committee review of the subcommittee's revised proposal beside the department's, and states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("August 13, 2026", "The status strip is re-scoped from live status to a dated record, and is now written by tools/sync-status.py, which holds the site's status facts once and writes every page that shows them. The strip's label now carries the date of the newest status change it states, currently July 27, and the strip closes by naming Where things stand as the page that holds the current state of the rulemaking, because a record page carrying a live status block is how this page came to say, for a day, that the committee recommendation was undelivered. The hero stamp read July 25 while the strip beneath it stated the July 27 submission; it now carries the date of this change."),
        ("July 28, 2026", "The page name is now the same in the title, the heading, and the menu: the training-hours record. The title had read \"Training Hours: The Tabled Numbers and the July 17 Decision\" and the heading \"Training hours\", which is the name of a different page."),
        ("July 25, 2026", "The specialization section moved off this page onto Specialized domains, which already held the same subject, so the two are no longer split across pages. What moved: the addendum framing, the core-baseline and end-of-life range cards, the nine-session curriculum table, and the questions left open for the training committee. What is left here is a pointer at the same anchor, so links in from other pages still land. Two boxes were dropped rather than moved, because Specialized domains already carried both: the four qualifying-condition domains as parallel options, and whether the hours belong in the core or in a separate add-on."),
        ("July 25, 2026", "Role tiles reordered to certifying clinician, practitioner, facilitator, as asked. The totals could not be reconciled with the rows above them: the tile listed 30, 5 and 5 while the total read \"35 + 100\". Totals now read \"35 didactic + 5 sim + 100 practicum\" and the rows name their units, so the arithmetic is visible."),
        ("July 25, 2026", "Page review applied. Removed the \"Purpose and how to read this page\" panel: a page that needs instructions for reading it has already failed. Added Dr. Anne Metz's proposed alternative permit title as a parenthetical under the Practitioner tile, since that is a separate recommendation that can be dropped without affecting the practicum work. Every entry in \"What changed on July 23\" now names its subsection in the sentence itself rather than relying on a link placed to one side."),
        ("July 25, 2026", "Brought current to the July 23 published rule. The page had no Updated date at all and was written in live-blog present tense from July 17: the Dr. Anne Metz presentation carried an \"In progress\" tag and a section was headed \"Open questions for July 17\". Role cards updated from the July 9 numbers to the published ones. Corrected two live errors: the in-state bridge deadline read June 30, 2027 and the reciprocity deadline read December 31, 2026, and both are December 31, 2027 in the published rule. Added a \"What changed on July 23\" summary."),
        ("July 17, 2026", "Added the live log of the July 17 Training and Education Committee meeting, including the Dr. Anne Metz presentation."),
    ],
    "pathways": [
        ("August 26, 2026", "A fourth route: the healing center, which the earlier page never carried although it is the certification a person opens a location under. Thirteen steps from the application at 7.35.3.11 through the operating duties at 7.35.3.20, stating what the rule does not require of the applicant, that it sets no application or certification fee, that a session still needs certified people in the room, and that the rule permits no provider ownership of a center and forbids none. Every starting license now shows it, because none of them is a prerequisite."),
        ("August 26, 2026", "Every route re-based to the August 25 text by tools/sync-pathways.py: the doubled module, the stated license scopes, the relettered waivers, every page anchor re-cited against the new PDF, and the roles at their published names with the recommendation notes reframed against the published text."),
        ("August 24, 2026", "An accuracy pass corrected the page: the step citations point at the pages that carry their provisions, the facilitator entry credential cites 7.35.3.9 (F), the certifications step carries the New Mexico EMT alternative, the controlled-substance step reads settled, kept by the department July 17, and the legend and lede were re-based to the current state."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "Every route re-based to the current state: the July 23 publication and its August 28 hearing were set aside, and the steps read from the last published text until revised rules publish. The what-if lines on the open steps now state the recommendation at its August 21 position, a staged practicum of 102 or 114 hours with the 18-hour case presentation and consultation group inside the total, in place of the July 27 figures of 60 or 70 with 20 consultation hours after."),
        ("August 21, 2026", "The source note now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("August 13, 2026", "The selection is now in the address. Picking a starting license, or a route under it, writes the choice into the URL as #start followed by the license's id, with &permit and the route's key added when the shown route is not that license's first, so the page a reader is looking at can be shared as a link and the link lands with the same panel and the same route open. A link carrying a value the page does not hold falls through to the default with nothing shown or hidden along the way. Without JavaScript the address changes nothing, and the page reads in full as before. The second table on Which licenses qualify links into these addresses from every verdict cell in the bands the starting licenses summarize."),
        ("August 13, 2026", "Every starting license, every route, and every step is now written into the page itself, by tools/sync-pathways.py, instead of being built by JavaScript when the page loads. Nothing a reader sees has changed: the profiles, the verdicts, the steps, the status flags, the citations, and the notes on what the committee recommendation would change all read exactly as before. What changed is that a browser's find command now reaches every step, a search engine can index them, and a reader without JavaScript is shown every starting license in turn, each with all of its routes, rather than a pointer to another page."),
        ("July 31, 2026", "A sixth starting point added, for a specialty that is not itself a New Mexico license, with the palliative care specialist and the hospice clinician as its examples. Its routes state that the certifying clinician and practitioner verdicts are set by the license the person holds, and that the facilitator route is open whatever license that is, because it turns on none. The end-of-life doula is named among the examples on the no-health-license start, where the facilitator route now states that a doula enters on the same terms as any other applicant and that the rule gives a doula no permit or scope, allowing any other individual to be present at an administration session on each patient's prior written consent at 7.35.3.20 (D). Three citations corrected on the practitioner and facilitator routes: the two practicum steps and the supervisory-hours step cited 7.35.3.18, and the practicum is 7.35.3.19, with the hour figures at Subsection A, pages 12 to 13, and the 20 supervisory hours at Subsection C, page 13, which sit inside the 120 rather than adding to them. The recommendation note on the two didactic steps read \"80 didactic hours in place of 35\" while the working model of the hours compared 80 against a module total of 40. The submission settles it: the recommendation page states its 80 across nine content areas running from 20 hours in core psychotherapy skills and ethics down to 2 hours in simulated patient work, so the 80 counts simulated patient hours inside the total exactly as the published 40 does. Both notes now say so and name the published 40 as the figure that compares."),
        ("July 28, 2026", "The two practicum steps, one on each of the practitioner and facilitator routes, now link the working model of the hours, which is where the quantities they state can be moved. The footer link to the record page read \"Recent developments\", a name that page no longer carries, and now reads \"Meetings and filings\". The page name is now the same in the title, the heading, and the menu: routes to a permit."),
        ("July 27, 2026", "Restored. The July 27 redesign merge replaced this page with a redirect; it returns unchanged from the July 25 version except for this: the committee recommendation is now recorded as submitted to the department on July 27 as a summary of the recommended rules, and the recommendation notes beneath the steps carry the submitted figures, 80 didactic hours, a 60 or 70 hour staged practicum by role, 20 hours of case presentation and consultation, and the renaming of practitioner to licensed provider, in place of the July 17 presentation ranges."),
        ("July 25, 2026", "Rebuilt. The page now says what it is in a lede, which it did not. Every step that the committee recommendation would change now shows the change directly beneath it, so a reader sees the published requirement and the proposed one together: 84 didactic hours in place of 35, a 62 or 72 hour scaffolded practicum in place of 100 or 120, supervisory hours from 20 to 10, and mentoring replaced by consultation with two presented cases. The certifying clinician route carries no such note, because the recommendation addresses facilitators and practitioners only and nothing on that route changes. The specialized-domain material from July 16 moved to its own page, and the JavaScript that rendered it was removed rather than left orphaned."),
        ("July 25, 2026", "Reviewed and brought current to the July 23 published rule. All route steps re-cited: the citation helper and 25 step links pointed at the superseded July 9 draft and now point at the published rule with section numbers. The practitioner core module was corrected from 25 hours to 30. \"Administration and same-day therapy sessions\" corrected to \"administration day sessions\". The status legend said the committee \"meets 1 PM today\" and now states that the hours were published unchanged on July 23 with the committee recommendation in progress. The reciprocity waiver step read December 31, 2026; the published rule reads December 31, 2027. The note about the draft's internal inconsistency on certifying-clinician reciprocity was rechecked against the published text, where reciprocity now sits inside 7.35.3.10, and the inconsistency persists."),
    ],
    "eligibility": [
        ("August 26, 2026", "Both tables re-based to the August 25 text: the curriculum cells at 65 plus 5 didactic with 10 simulated, the entry credentials carrying the stated license scopes, the scope-test section recording that the text now writes the scopes into the application items, the what-if block reframed against the published figures, and the roles at their published names."),
        ("August 24, 2026", "An accuracy pass corrected the page: the didactic and mentoring pills read open and the controlled-substance pill settled, the alternative-route sentence states the three bases 7.35.3.10 accepts, the sources block frames the July 23 text as the last published text, set aside, and every speaker is named in full."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "The table note and the what-if block re-based to the current state: the July 23 publication was set aside, the tables read from the last published text, and the what-if block states the recommendation at its August 21 position, 102 and 114 practicum hours with the consultation group inside the total and 22 hours as the largest content-area minimum, in place of the July 27 figures."),
        ("August 21, 2026", "The table note now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("August 13, 2026", "Copy pass on the three sections added July 31: the scope test, every role the rule names, and the chaplaincy and spiritual care section. Sentences written as argument are restated as reference and headings name their contents; no figure, citation, verdict, or quoted passage changed."),
        ("August 13, 2026", "The scope-test section now records the question the supervised tiers leave open: if a supervised licensee were certified as a practitioner, would the clinical supervisor their own board requires also need a permit under this program? No document and no meeting record held in this repository asks it. The published rule's supervision language sits entirely inside the program, the facilitator under the direct supervision of a practitioner at 7.35.3.13 (B) and the practicum supervision at 7.35.3.19, and never reaches the supervision a supervised license carries from its own licensing board. A starting point for the supervised tiers on Routes to a permit waits on that answer."),
        ("August 13, 2026", "Every verdict cell in the second table now carries a small route link into Routes to a permit, landing with the matching starting license selected, and with the matching route open where that page offers one. The prescribing and medical band lands on the license-to-diagnose start, the independent behavioral health band on the therapy-or-counseling start, the other-licensed-health band on the other-health-license start, the non-clinical and community band on the no-health-license start, the specialty band on the specialty start, and the out-of-state band on the trained-outside-New-Mexico start. Two rows leave their band's mapping because their verdicts do not: the psychiatric mental health nurse practitioner lands on the license-to-diagnose start, whose three verdicts match that row, and the psychiatric clinical nurse specialist on the therapy-or-counseling start. The supervised behavioral health band carries no route links, because no starting license on Routes to a permit summarizes a supervised tier. A cell graded No current path or Not specified, and any cell whose column that start does not open, links the starting license alone, because there is no route to show. The section on the end-of-life doula and the palliative care specialist links both of its readings the same way. Existing links on the cells, to the controlled-substance number page, the scope test, and that section, are kept beside the new ones."),
        ("July 31, 2026", "A section maps chaplains, pastoral counselors, and spiritual care, a group that sits outside the licensing system entirely. No state in the United States licenses, certifies, registers, or title-protects a chaplain, and New Mexico issues no chaplain credential of any kind; the national certifications are private and are made compulsory by hospitals rather than by governments. Pastoral counselor is a licensed title in six states, New Mexico is not among them, and contemporary accounts state those laws were passed principally so that pastoral counselors could bill insurance, which makes them a precedent about payment rather than competence. The certification a New Mexico statute once pointed at, from the American Association of Pastoral Counselors, no longer exists: that body stopped certifying and dissolved in March 2019 and no successor inherited the credential. Two New Mexico exemptions carry this population instead, one of which expressly covers practitioners of Native American healing arts, and neither is a route into this program because an exemption is permission to practice without a license rather than a license. The consequence under the rule is stated plainly: none of it qualifies a person and none of it disqualifies one, because the certifying clinician and practitioner routes need a New Mexico license that a national certification is not, and the facilitator route asks for no license at all, so a board certified chaplain and a person holding nothing stand in the same position. The section also records that the Board of Chaplaincy Certification already credits up to 7,200 hours of mentored study in place of a graduate degree for applicants trained in Buddhist and Indigenous traditions, which is a worked example of the recognition question the legacy pathway raises. The whole section carries Need source marks, because none of the underlying statutes or certifying-body standards is held in this repository and none has been read directly.")
        ,("July 31, 2026", "Two additions. The scope-test section now states who may issue a certification the rule asks for: the rule names an issuer only where it writes New Mexico, and every other credential it requires, being basic life support, cardiopulmonary resuscitation, automated external defibrillator, HIPAA, wilderness first aid and wilderness first responder, is named with no issuer at all. The words national, nationally and accredited appear nowhere in the 19 pages. That decides the question for anyone holding a national board certification rather than a state license: it cannot satisfy Paragraph (1) of Subsection D or E of 7.35.3.9, and it does not need to, because the facilitator route asks for no license. The role map gains the co-facilitation route. Nothing requires one person to hold the whole role, and Paragraph (5) of Subsection H of 7.35.3.20 already puts a practitioner and a facilitator in every individual session, with Subsection B of 7.35.3.13 setting the relationship. A traditional healer, chaplain, peer supporter or death doula can be the certified facilitator, which requires no license, working alongside a licensed practitioner, so the pair satisfies the rule where the individual does not. Two limits are stated with it: Subsection B of 7.35.3.13 bounds a facilitator to peer support and logistical and administrative support, and Subsection D of 7.35.3.19 still requires every practicum hour inside an approved location.")
        ,("July 31, 2026", "The page now maps every route into the program rather than the three permits alone. Table 2 gains eleven license rows: the professional art therapist, whose statutory scope is the licensed practice of counseling or therapy services and which therefore grades as a clinical counselor does; the alcohol and drug abuse counselor; the supervised tiers LMHC, LMHC-AS, LAMFT, LMSW and psychologist associate; LBSW and LSAA; the psychiatric nurse practitioner and clinical nurse specialist; the occupational therapist; and the certified peer support worker, certified community health worker, New Mexico-certified perinatal doula, and creative arts therapists other than art therapy. Two verdicts are added to the legend because the rule cannot express what New Mexico actually licenses. Supervised only marks a scope that reaches the work under a supervisor the rule never accounts for. One condition marks the alcohol and drug abuse counselor, whose scope reaches substance use disorder and expressly excludes mental health disorders, which makes it the first verdict on the site that runs by condition rather than by license. A section states the scope test itself, that it defers to each licensing board, that the published rule does not restate it, and that the controlled-substance number rather than scope is what holds the certifying column at Partial. A second section maps every role the rule names, grouped by how a person comes to hold it: certified on application; authorized to handle the medicine without being certified, which is the healing center owner and employee whose registration the rule never creates; required on site with a credential from somebody else, which is the wilderness first aid or EMT pair for remote outdoor sessions; engaged privately with criteria the department never checks, which is the third-party evaluator, the instructor, the certified faculty member and the practicum supervisor; present by the patient's consent; and named in the record with no route in the rule. The fourth class, admitted under 7.35.3.20 (D) as \"the other individual(s)\", is named in full for the first time: support person, space attendant, end-of-life doula, chaplain or religious leader, interpreter, caregiver, and traditional healer or elder, none of which appears anywhere in the rule, together with the four consequences that follow from the class being unnamed. The doula paragraph is rewritten around a fact that changes it: New Mexico credentials doulas under the Doula Credentialing and Access Act, with a registry and a Medicaid pathway, and scopes that certification to birth, so the end-of-life doula falls outside a framework that exists rather than one that does not. Anything asserted from a source this repository does not hold now carries a Need source mark, which is a legend entry of its own, so unfinished sourcing is visible on the page instead of being invisible.")
        ,("July 31, 2026", "Two starting points added that the second table did not carry. The end-of-life doula, also called the death doula, joins the non-clinical and community band, graded No current path for certifying clinician and practitioner and Eligible for facilitator: 7.35.3.9 (D) and (E) each require a current New Mexico professional license, New Mexico issues none for doulas, and 7.35.3.9 (F) requires no license at all. The palliative care specialist sits in a new band, a specialty rather than a license, because palliative care is a field of practice and the rule never grades a specialty. Its two licensed columns read By license held, a new verdict added to the legend, and its facilitator column reads Eligible. A section beneath the table reads both routes in full, names which existing row each kind of palliative care worker is read on, and records the second question separately: 7.35.3.20 (D) allows any other individual to be present at an administration session on each patient's prior written consent, while the rule gives neither role a permit, a scope, a training standard, or a place in the staffing ratio at 7.35.3.20 (H)(5). Larry Leeman named that gap at the July 16 End-of-Life Care committee meeting, and the rule published July 23 does not close it. A block above that section now states two limits on the second table. The rows are starting points rather than the set of New Mexico licenses, because no document in the chain lists licenses: the Act defines one provider role, 7.35.2 NMAC defines a practitioner as a licensed healthcare professional, the published rule gives parenthetical examples, and the only scope-of-practice test in the chain sits in the June 12 recommendation, which the published rule does not restate. And the certifying clinician column carries one verdict where the rule needs one per condition, because 7.35.3.8 (B)(8)(a) requires an attestation of a qualifying diagnosis and the qualifying conditions are not one kind of thing, so no behavioral health license establishes end-of-life care and that pathway is gated by a medical prognosis at its first step. Separately, the block on what the committee recommendation would change described its classroom figure as \"a single 80-hour standard\" without saying what it replaces or what it counts. It now states the published 40 it stands against, and that the submission spreads its 80 across nine content areas from 20 hours in core psychotherapy skills and ethics down to 2 hours in simulated patient work, so the two figures count the same things and compare directly."),
        ("July 28, 2026", "The hero stamp read July 25 while the block beneath the tables stated the July 27 submission, so the page disagreed with itself about its own date. The stamp now reads July 28 and says what the recommendation would change, that nothing in the tables changes unless the department adopts it, and links the block. The tooltip on the nine certifying-clinician verdict cells moved from the title attribute, which a touch device never shows, to the data-cite attribute the rest of the site uses for citation disclosure. The page name is now the same in the title, the heading, and the menu: which licenses qualify."),
        ("July 25, 2026", "Both tables re-ordered to certifying clinician, practitioner, facilitator, the order used on the other provider pages. Every hour figure and every eligibility pill was then checked against the published rule, and five things were wrong. The certifying clinician's prerequisites read \"License only\"; 7.35.3.9 (D) also requires HIPAA certification completed within the preceding two years and the sex-offender attestation, so the cell now names those and says the BLS, CPR and EMT requirement does not apply to that role. The approved-program row named only the role curricula; 7.35.3.18 (A) requires the New Mexico module of all three, so all three cells now name it. Both out-of-jurisdiction rows graded the certifying clinician column \"Not specified\"; 7.35.3.10 (B) names certifying clinician alongside practitioner and facilitator, so both are now Reciprocity, and the note under the table states how that route works instead of saying there is no packet for it. The source notes under both tables cited pages the material is not on: table 1 pointed at p.11 for content described as pp.4-9, and table 2 pointed at p.2 for entry credentials that are on p.3. Both now cite each subsection to its own page. The \"If the committee recommendation is adopted\" block appeared twice in a row; one copy was removed. Every remaining figure was confirmed correct: 8 didactic and 8 CME hours for the clinician, 30 shared and 5 role-specific didactic with 5 simulated patient hours, 100 and 120 practicum hours, 20 supervisory hours, 10 mentoring hours, and 20 continuing education hours."),
        ("July 25, 2026", "The two links to the proposed specialization hours pointed at Training hours, which no longer holds them; both now point at Specialized domains."),
        ("July 25, 2026", "Figures corrected. The practicum read \"~100 hours\" and \"~120 hours\"; the rule says a minimum of 100 and 120, so the tildes are gone. The prerequisites row read \"BLS, HIPAA, attestation\" and now records that the published rule accepts BLS, or CPR and AED, or New Mexico EMT licensure. The curriculum row named a curriculum without ever giving its hours, and now states 30 shared plus 5 role-specific didactic with 5 simulated patient hours, and 8 for the certifying clinician. Added a block setting out what changes if the committee recommendation is adopted, including that the certifying clinician does not change."),
        ("July 25, 2026", "Reviewed and brought current to the July 23 published rule. Both tables re-cited from the July 9 draft to the published rule with section numbers. The reciprocity entry read that the draft set two waiver deadlines of December 31 2026 and June 30 2027; the published rule sets both at December 31, 2027, and the older dates are kept only as history. Four links whose text named the published rule while still pointing at the July 9 PDF were repaired."),
    ],
    "cs-number": [
        ("August 26, 2026", "The liability section rebuilt on the New Mexico authorities themselves, and its balance corrected: the annotations to 41-5-3 state that an examination a person must undergo as a condition of obtaining something creates a duty to the examinee, which is the closest analog to this role and runs toward exposure; Wilschinsky and Lester hold the third-party duty narrow; Del Sol keeps foreseeability out of the duty question; and the Act's Section 5 is the cannabis certifier clause of 26-2B-4 with two words changed."),
        ("August 26, 2026", "The liability analysis moved out of the collapsed context blocks into a numbered section, rebuilt on New Mexico authority: Rodriguez v. Del Sol holds that foreseeability is not a factor in deciding whether a duty exists, which is the route the out-of-state case relied on, so that case is now stated as illustration rather than prediction; the Act's Section 5 protection is stated as the policy the legislature has already declared; and the Medical Malpractice Act question is stated as open on the definitions in 41-5-3."),
        ("August 26, 2026", "The Medical Psilocybin Act entered the page as a held primary source: the Act's clinician is defined as the provider of the three sessions, so the Act places the appropriateness judgment with the treating provider; the Section 5 exemption protecting a clinician from penalty for recommending the program is quoted; and the open registrant count now records what was searched and the two routes that would produce the number."),
        ("August 26, 2026", "The certification language box now leads with the published text: 7.35.3.8 (B)(8)(c) as published August 25, quoted verbatim, with the note that against the language stated July 17 and published July 23 the August 25 text changed one word, formal consult in pathway (iii) becoming formal consultation, and every other word is identical."),
        ("August 26, 2026", "Rebuilt at a third of the visible length around the routes to the number: an answer block, a no-one-prescribes-psilocybin statement, a route table for each starting license linked to the eligibility and routes pages, the open registrant count stated as open, and the comparators, telemedicine precedents, liability framework, and rural supply demoted into collapsed context blocks with nothing deleted."),
        ("August 26, 2026", "The page carries the third home of the requirement: the amended definition of certifying clinician in 7.35.2.7, published August 25, holds the controlled-substance number inside it. Citations re-anchored to the August 25 PDF, the patient-application cite moved to page 2, and the hearing stated as fixed by notice."),
        ("August 24, 2026", "An accuracy pass corrected the page: the July 9 quotations carry the transcript's exact words with every elision marked, the agency is named the Regulation and Licensing Department, the starting-point count reads thirty-seven, and the standing text reports the set-aside in place of a currently proposed rule."),
        ("August 24, 2026", "Role vocabulary entered the site's own voice: the middle role is the Licensed Provider, the recommendation's name for the role the published text calls the practitioner, and the screening role is written certifying clinician / medical screener, the recommendation's proposed rename, still being pushed. Verbatim quotes and provision names keep the documents' own words."),
        ("August 24, 2026", "The update line and the open-questions section re-based: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules; the requirement stands in the last published text."),
        ("August 21, 2026", "The update line and the open-questions section now state the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("July 28, 2026", "The update section now closes with a line back to the two pages that send readers here, the license tables and the routes, because a reader arriving from a verdict cell had no way back into their own situation. The page name is now the same in the title, the heading, and the menu: the controlled-substance number, with the site's title suffix, which this page alone had been carrying without."),
        ("July 25, 2026", "First full review of this page. Its central citation was wrong in two places: the lede and section 1 cited the controlled-substance-number requirement to 7.35.3.13 on p.8, which is the clinician-patient relationship and telemedicine section and contains no such requirement. The requirement is at 7.35.3.9 (D)(2), p.3, and a second location the page never mentioned, 7.35.3.8 (B)(3), p.1, which requires every patient enrollment application to record the certifying clinician's controlled substance number. Section 1 stated as verified that the state application requires a current DEA registration and that the state number must be obtained before the DEA issues the federal one, which is circular and which the July 17 record puts in dispute; it now states the dispute and that the department is checking with the Board of Pharmacy. The hearing was described as something the department was targeting for the end of August, which was accurate on July 17 and was superseded when the rule was published with the hearing set for August 28. Three sections ended at a decision point that has since been decided: section 2 called the non-prescribing certifying clinician an open rulemaking question, section 4 ended with the board sending the question back to the department on July 9, and section 6 presented telemedicine only as an external federal precedent when the published rule now contains a telemedicine pathway of its own at 7.35.3.13 (A)(2), p.8. All three now carry the outcome. The update section was dated to July 17 and now runs through the July 23 publication. The footer said the page was compiled July 9 from the record through the July 9 meeting."),
        ("July 25, 2026", "Reviewed and brought current. The page had no Updated date; one was added. The note that \"the July 9 draft PDF still shows the earlier text; an updated draft document has not been posted\" is no longer true: all three certifying-clinician exam pathways appear in the published rule at 7.35.3.8 (B)(8)(c) and 7.35.3.13 (A)(2), and the note now says so. Citations repointed to the published rule. No change to the substance of the page, which was accurate."),
    ],
    "changes": [
        ("August 26, 2026", "A new top layer, August 25 against July 23: the doubled module, the practicum evaluation, the license scopes, the role definitions, and the changes beyond the training sections, with the July 23 layer reframed as history and kept unedited."),
        ("August 24, 2026", "An accuracy pass corrected the page: the July 23 text is framed as the last published text, set aside, rather than the current text, the update stamp carries August 24, and the 7.35.3.10 (D) cite moved to page 5."),
        ("August 24, 2026", "The lede and the hearing note re-based: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules; the diffs read from the last published text until revised rules publish."),
        ("August 21, 2026", "The note under the diff layers now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("July 28, 2026", "Every provision on the page can now be linked from outside it: the thirteen published-provision rows carry section anchors in the same form the practicum worksheet uses, and each of the 104 comparison entries carries an anchor derived from its heading. The July 26 copy audit was applied: \"Dr. Ann Metz\" is corrected to \"Dr. Anne Metz\" in three places, \"Warnock\" is given as Catherine Warnock, and the deferrals log now states how its attributions are sourced and names the six rows that carry a first name alone, because no surname for them appears in any document this site holds. The four notes that told a reader to verify a passage against the source PDF were resolved instead: all four readings are confirmed against the July 9 draft at pages 5, 8, 11, and 14, and each note now states the finding and links the page. The page name is now the same in the title, the heading, and the menu: section by section."),
        ("July 25, 2026", "Added the CSS rules for the body, citation and note classes used in the published-provisions section, which had none on this page and were rendering unstyled."),
        ("July 25, 2026", "Page review applied. The section headed \"Earlier layer, 104 provisions\" told a reader nothing and is now \"Where the rules came from\", with a heading that says what the comparison actually is. The published-provisions table states in its opening line that these are the provisions deferred to the committee, rather than leaving it to be found. The \"Change from July 9\" column can now be hidden, since it is context rather than the thing most readers came for."),
        ("July 25, 2026", "Restructured into layers rather than re-citing 108 anchors that were already correct for what they compare. A new section, \"The training and education provisions, as published\", now leads the page: thirteen provisions with the July 23 text, the section and page, and what changed from July 9. It covers the didactic increase from 25 to 30 hours, the unchanged practicum, the new rule that the practicum cannot begin before half the didactic and all simulated patient hours, both waiver deadlines moving to December 31 2027, the disagreement between the two waivers on group session counts, and the new qualified-student staffing ratio. The existing 104-provision comparison was mis-framed as the current draft when it is a comparison of the June 12 recommendation against the July 9 draft; it is relabelled as the earlier layer and kept intact, with its July 9 page anchors, which are correct for that comparison."),
    ],
    "deferred": [
        ("August 26, 2026", "Re-verified against the August 25 text: every quote re-extracted, the subsections relettered around the new practicum evaluation at 7.35.3.19 (C), which enters as its own provision, and the three not-working-as-written findings recorded as carried forward unchanged."),
        ("August 24, 2026", "An accuracy pass corrected the page: the 7.35.3.19 (B) and 7.35.3.10 (D) cites moved to the pages that carry those subsections, and the description of 7.35.3.19 (A) reports the rule's permissive list, to experience, observe, or conduct supervised facilitation."),
        ("August 24, 2026", "The update line re-based: the July 23 publication and its August 28 hearing were set aside, the July 23 text stands as the last published text, and the committee's recommendation stands at its August 21 position, in the department's hands for the revised rules."),
        ("August 21, 2026", "The update line now states the schedule as restated: the department stated at the August 21 committee meeting that revised proposed rules publish August 25 and that the rule hearing, first set for August 28, is anticipated for October 2, with the final notice to fix the date."),
        ("July 28, 2026", "Every provision block now carries a link to the same section on the published rule page, and the two provisions that do not exist in the rule carry one as well, so the reference runs in both directions. The reciprocal links from the rule page's defect notes to findings B1, B4, and B5 landed in the same pass. The page name is now the same in the title, the heading, and the menu: what a practicum change touches."),
        ("July 27, 2026", "Restored. The July 27 redesign merge replaced this page with a redirect; it returns unchanged from the July 25 version. The committee recommendation on the deferred hours reached the department the same day; nothing on this page changes with it, because this page quotes the published text."),
        ("July 25, 2026", "Rebuilt as a worksheet. The first version led with a reading guide and a three-column history of how each requirement reached the published text, which is not what this page is for; that history belongs on the History page. The page now lists the thirteen provisions a practicum change has to touch, quotes each from the published rule, states what it does, and flags the three that do not work as written: 7.35.3.14 authorises nobody to let a student handle psilocybin, 7.35.3.19 (G) and 7.35.3.10 (D)(1) set different session tests for the same 40-hour waiver, and 7.35.3.14 (C) conditions healing-centre authority on a registration no section creates. Two provisions were added after checking the dependency chain: 7.35.3.11, which creates the approved locations 19 (D) requires, and 7.35.3.10 (D)(1), the second practicum waiver. The reading guide and the closing scope section were removed. All eighteen quotation fragments verified against the published text."),
    ],
    "about": [
        ("August 24, 2026", "An accuracy pass corrected the update stamp, which carries the date of the page's latest logged revision."),
        ("August 13, 2026", "A per-page revision log returned to every content page of the site, this one included, written by tools/sync-provenance.py, and the corrections sentence now names the log beside the repository history as where a correction is recorded."),
        ("July 28, 2026", "The page name is now the same in the title, the heading, and the menu: how this site is built."),
        ("July 28, 2026", "One grouped menu on every page replaced the flat seven-item navigation, with the Documents dropdown at its right edge, and every stylesheet link now carries the style.css content hash so a page and its styles arrive from the same deploy."),
        ("July 27, 2026", "Created in the July 27 redesign: method and trust. The verification ladder returned as the spine of the Method section the same day, with the one standing soft point named, the June 26 attribution."),
    ],
    "specialization": [
        ("August 26, 2026", "The core figures re-based to August 25, 70 didactic plus 10 simulated, and the where-end-of-life-sits note re-read against the new topic list: twenty-six topics, end-of-life still not among them, with the new qualifying-conditions topic named as the nearest counterpart."),
        ("August 24, 2026", "An accuracy pass corrected the page: the last published text is named as such throughout, and the hours cross-reference describes the model's comparison of the recommendation against the last published text."),
        ("July 31, 2026", "The core-baseline card stated \"35 didactic + 100 practicum\" and said the working model of the hours held the same figures, which it did not: the model compares module totals, so its published baseline is 40. The card now names the 5 simulated patient hours as their own quantity and states which basis the model uses, so the two pages no longer disagree about the same rule text."),
        ("July 28, 2026", "The July 16 material now states how it is sourced before it states anything else: no recording, transcript, or minutes of that meeting is held in this repository, the absence is registered on the record page, and every source line beneath says so. Dom is named as Dominic Zurlo, director of the Department of Health Center for Medical Cannabis and Psilocybin, with the note that the July 16 notes recorded him by first name. Space Attendant is defined where it first appears. Jenn, Jamie, and Christine keep the first names the notes recorded, because no surname for them appears in any document this site holds, and the page now says that rather than leaving it to be noticed."),
        ("July 27, 2026", "Restored. The July 27 redesign merge replaced this page with a redirect; it returns unchanged from the July 25 version except that the core-figure link points at the retained record page, training-hours-record.html, where the pre-redesign Training hours material lives."),
        ("July 25, 2026", "This page now holds the specialization hours, which had been maintained on Training hours as well. Added at a new #hours anchor: the addendum framing, the core-baseline and end-of-life range cards, the nine-session 17-hour curriculum presented on July 16, and the three questions left open for the training committee. The banner said \"The routes above are unchanged\", which was left over from when this material sat at the foot of the provider routes page and there were routes above it."),
        ("July 25, 2026", "Page created from the specialized-domain section that was previously at the foot of the provider routes page, where it sat below unrelated material and carried July 16 dates with no indication of their status. It now states that none of it is in the published rule. Added the citation showing where end-of-life sits in the published text: the curriculum at 7.35.3.18 (C) lists seventeen required subjects and end-of-life is not among them, nor are suicidality, substance use disorder or PTSD, all four of which were asked for on the record on July 17."),
    ],
}

CSS = """  .prov{margin:26px 0 0; border:1px solid var(--border-strong); border-radius:12px; background:var(--surface); overflow:hidden;}
  .prov>summary{list-style:none; cursor:pointer; padding:13px 16px; display:flex; align-items:center; gap:10px; font-size:13.5px; color:var(--text-muted); background:var(--surface-2);}
  .prov>summary::-webkit-details-marker{display:none;}
  .prov>summary:hover{color:var(--text);}
  .prov .provsum{font-weight:650;}
  .prov .provchev{margin-left:auto; font-size:11px; transition:transform .15s;}
  .prov[open] .provchev{transform:rotate(90deg);}
  .provbody{padding:4px 16px 18px;}
  .provsec{margin-top:16px;}
  .provk{font-size:11px; font-weight:700; letter-spacing:.09em; text-transform:uppercase; color:var(--accent); margin:0 0 10px;}
  .provsec .cd{font-size:12px; font-family:var(--mono); color:var(--text-faint); margin:0;}
  .provsec .cn{font-size:14.5px; font-weight:650; color:var(--text); margin:1px 0 0;}
  .provsec .cw{font-size:13.5px; color:var(--text-muted); line-height:1.55; margin:6px 0 0;}
  .provsec .curflag{display:inline-block; font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; color:var(--agree); background:var(--agree-bg); border:1px solid var(--agree-border); border-radius:20px; padding:1px 8px; margin-left:7px; vertical-align:1px;}
  .revs{list-style:none; margin:0; padding:0;}
  .revs li{font-size:13.5px; color:var(--text-muted); line-height:1.55; padding:8px 0; border-top:1px solid var(--border);}
  .revs li:first-child{border-top:none; padding-top:0;}
  .revs b{color:var(--text); font-weight:650;}
"""

MARK = "<!-- provenance: generated by tools/sync-provenance.py, do not hand-edit -->"
BLOCK_RE = re.compile(re.escape(MARK) + r".*?" + re.escape("<!-- /provenance -->"), re.S)
CSS_MARK = "/* provenance block */"
CSS_RE = re.compile(re.escape(CSS_MARK) + r".*?" + re.escape("/* /provenance block */"), re.S)


WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
         7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build(page):
    cur = next(c for c in CHAIN if c["status"] == "current")
    superseded = len(CHAIN) - 1
    chain = (
        '          <p class="cd">{date}</p>\n'
        '          <p class="cn"><a href="{file}" target="_blank" rel="noopener">{name}</a>'
        '<span class="curflag">Current state of truth</span></p>\n'
        '          <p class="cw">{what}</p>\n'
        '          <p class="cw">This document supersedes {n} earlier ones. Each of them, what it '
        'is, what superseded it and when, and a download, is in the register at '
        '<a href="record.html#documents">Meetings and filings</a>.</p>'
    ).format(date=syncrecord.long_date(cur["date"]), file=cur["file"], name=esc(cur["name"]),
             what=esc(CHANGED[cur["slug"]]), n=WORDS.get(superseded, superseded))

    revs = REVISIONS.get(page)
    if revs:
        items = "\n".join(
            f'          <li><b>{d}</b> {esc(t)}</li>' for d, t in revs
        )
        revblock = (
            '        <div class="provsec">\n'
            '          <p class="provk">Revisions to this page</p>\n'
            '          <ul class="revs">\n' + items + "\n"
            "          </ul>\n"
            "        </div>\n"
        )
    else:
        revblock = ""

    return (
        f"{MARK}\n"
        '      <details class="prov">\n'
        '        <summary><span class="provsum">Provenance: the source document and this page&rsquo;s revisions</span><span class="provchev">&#9656;</span></summary>\n'
        '        <div class="provbody">\n'
        '        <div class="provsec">\n'
        '          <p class="provk">The document this page is read from</p>\n'
        + chain + "\n"
        "        </div>\n"
        + revblock +
        "        </div>\n"
        "      </details>\n"
        "      <!-- /provenance -->"
    )


def main():
    check = "--check" in sys.argv
    changed, ok, stubs, missing = [], [], [], []

    for path in sorted(glob.glob(os.path.join(DOCS, "*.html"))):
        name = os.path.basename(path)
        page = name[:-5]
        src = open(path).read()
        if 'http-equiv="refresh"' in src:
            stubs.append(name)
            continue

        new = src
        block = build(page)
        anchor = '<div class="sitefoot">'
        if anchor in src:
            # A restored page: the block sits before the sitefoot, and its
            # styles are injected into the page's own stylesheet.
            css_block = CSS_MARK + "\n" + CSS + "  " + "/* /provenance block */"
            if CSS_RE.search(new):
                new = CSS_RE.sub(lambda _: css_block, new, count=1)
            else:
                new = new.replace("</style>\n<style id=\"navpass\">", css_block + "\n</style>\n<style id=\"navpass\">", 1)
            if BLOCK_RE.search(new):
                new = BLOCK_RE.sub(lambda _: block, new, count=1)
            else:
                new = new.replace(anchor, block + "\n      " + anchor, 1)
        elif "</main>" in src:
            # A redesign-idiom page: the block closes main, and the shared
            # style.css carries the .prov rules.
            if BLOCK_RE.search(new):
                new = BLOCK_RE.sub(lambda _: block, new, count=1)
            else:
                new = new.replace("</main>", "  " + block + "\n</main>", 1)
        else:
            missing.append(name)
            continue

        if new == src:
            ok.append(name)
        elif check:
            changed.append(name)
        else:
            open(path, "w").write(new)
            changed.append(name)

    for n in changed:
        print(("STALE       " if check else "updated     ") + n)
    for n in ok:
        print("in sync     " + n)
    for n in stubs:
        print("stub        " + n)
    for n in missing:
        print("NO ANCHOR   " + n)

    if missing:
        print("\n%d page(s) with no place for the block." % len(missing))
        return 1
    if check and changed:
        print("\n%d page(s) stale. Run without --check to fix." % len(changed))
        return 1
    print("\n%d page(s), provenance identical." % (len(changed) + len(ok)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
