#!/usr/bin/env python3
"""Generate the chain, the register, and the gaps register on docs/record.html.

record.html is the site's most update-frequent page, and until this tool existed
every event, every document row, and every stated absence was hand-written HTML.
The same document was then described twice in different words, once in a chain
entry and once in a register row, which is the drift pattern the redesign brief
names first. Three structures here hold that content once:

    EVENTS      every meeting, publication, filing, and scheduled or
                anticipated date, newest
                first, each with a stable anchor of the form e-YYYY-MM-DD, with
                -am or -pm appended where a day carries more than one event
    DOCUMENTS   the register: every document the site holds or cites, each with
                a stable anchor of the form doc-<slug>
    GAPS        the register of documents the site does not hold, each naming
                the event it belongs to

The three reference each other, and the references are checked rather than
trusted: an event attaches documents by slug, states an absence by gap id, and
every gap names its events. validate() below fails on a reference that does not
resolve, and on an absence a gap claims that its event does not carry back.

Text fields are HTML fragments. They carry their own links and entities, and
they are written to the standard in WRITING-STANDARD.md: every figure, date,
vote, and quotation comes from the published rule, a named transcript, or
another page of this site, and an absence is stated rather than left silent.

Four regions of docs/record.html are generated, each between its own markers,
and nothing outside them is touched: the page's own stylesheet block, the
chain, the register at #documents, and the gaps register at #gaps.

tools/check-site.py imports this module, which runs validate() at import, and
calls stale() to fail the build if record.html no longer matches the data.
tools/sync-provenance.py reads DOCUMENTS as well, for the four documents of the
drafting chain it names at the foot of the seven pages that carry a provenance
block, so the register is the one place a document's identity is written.

Usage:
    python3 tools/sync-record.py           # write the four blocks into record.html
    python3 tools/sync-record.py --check   # exit 1 if record.html is stale
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import partlib
PART = partlib.current_part()
DOCS = partlib.docs_dir(PART)
PAGE = os.path.join(DOCS, "record.html")

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

partlib.load_data(PART, "sync-record", globals())

CSS = r"""/* record: generated by tools/sync-record.py, do not hand-edit */
.chainnote,.regnote{font-size:14px;color:var(--ink2);max-width:76ch;margin:0 0 18px}
.event{display:grid;grid-template-columns:112px 1fr;gap:20px;padding:20px 0;border-top:1px solid var(--hair)}
.event:first-of-type{border-top:1.5px solid var(--ink)}
.ekey{font:650 12px var(--mono);color:var(--ink);line-height:1.6}
.ekey .yr,.ekey .pt{display:block;font-weight:400;color:var(--faint)}
.ekey .kd{display:block;margin-top:9px;font:650 9.5px var(--mono);letter-spacing:.15em;text-transform:uppercase;color:var(--ink2)}
.ebody{min-width:0;max-width:72ch}
.ewhat{font-size:14.5px;color:var(--ink2);line-height:1.6;margin:0;max-width:none}
.ewhat b{color:var(--ink);font-weight:650}
.elabel{font:650 9.5px var(--mono);letter-spacing:.15em;text-transform:uppercase;color:var(--faint);margin:16px 0 2px}
.elist{list-style:none;margin:0;padding:0;font-size:14px;color:var(--ink2)}
.elist li{padding:6px 0;border-top:1px solid var(--hair);line-height:1.55}
.elist li:first-child{border-top:none}
.elist b{color:var(--ink);font-weight:650}
.elist .w{font:12px var(--mono);color:var(--ink2)}
.elist .none{color:var(--faint)}
.esaid{margin-top:14px;border-left:2px solid var(--hair);padding-left:14px}
.esaid>summary{list-style:none;cursor:pointer;font:650 9.5px var(--mono);letter-spacing:.15em;text-transform:uppercase;color:var(--ink2);padding:2px 0}
.esaid>summary::-webkit-details-marker{display:none}
.esaid>summary::after{content:"\25B8";color:var(--faint);padding-left:5px}
.esaid[open]>summary::after{content:"\25BE"}
.ebasis{font-size:13px;color:var(--faint);line-height:1.55;margin:8px 0 2px;max-width:70ch}
.tscroll{overflow-x:auto}
.event,#documents,#gaps,.reg tbody tr,#gaps tbody tr{scroll-margin-top:70px}
.reg .fn{display:block;font:11.5px var(--mono);color:var(--faint);overflow-wrap:anywhere;margin-top:3px}
.reg .sup{display:block;font-size:12.5px;color:var(--ink2);line-height:1.5;margin-top:5px}
.reg td:nth-child(2){white-space:nowrap}
@media(max-width:620px){
  .event{grid-template-columns:1fr;gap:8px;padding:18px 0}
  .ekey{display:flex;flex-wrap:wrap;gap:10px;align-items:baseline}
  .ekey .yr,.ekey .pt,.ekey .kd{display:inline;margin:0}
}
/* /record */"""


# ---------------------------------------------------------------------------

BY_SLUG = {d["slug"]: d for d in DOCUMENTS}
BY_ID = {e["id"]: e for e in EVENTS}
BY_GAP = {g["id"]: g for g in GAPS}


def validate():
    """Fail on a reference that does not resolve, or an absence with no reciprocal."""
    problems = []
    if len(BY_SLUG) != len(DOCUMENTS):
        problems.append("two documents share a slug")
    if len(BY_ID) != len(EVENTS):
        problems.append("two events share an id")
    if len(BY_GAP) != len(GAPS):
        problems.append("two gaps share an id")

    for d in DOCUMENTS:
        if d["event"] not in BY_ID:
            problems.append(f"document {d['slug']} names event {d['event']}, which does not exist")
        if d["status"] == "superseded":
            if d.get("superseded_by") not in BY_SLUG:
                problems.append(f"document {d['slug']} is superseded by nothing that exists")
        elif d.get("superseded_by"):
            problems.append(f"document {d['slug']} is not superseded but names a successor")
        if d["status"] not in ("current", "superseded", "record"):
            problems.append(f"document {d['slug']} has status {d['status']!r}")
        if d["file"] and not os.path.exists(os.path.join(partlib.DOCS_ROOT, d["file"])):
            problems.append(f"document {d['slug']} points at {d['file']}, which is not in docs/")

    for e in EVENTS:
        if e["kind"] not in ("meeting", "document", "filing", "scheduled", "anticipated"):
            problems.append(f"event {e['id']} has kind {e['kind']!r}")
        if not e["id"].startswith("e-" + e["date"]):
            problems.append(f"event {e['id']} does not carry its own date")
        for slug in e.get("attached", []):
            if slug not in BY_SLUG:
                problems.append(f"event {e['id']} attaches {slug}, which is not in the register")
        for gid in e.get("absent", []):
            if gid not in BY_GAP:
                problems.append(f"event {e['id']} states absence {gid}, which is not a gap row")

    # R7 both ways: a gap names its events, and each of those events says so.
    for g in GAPS:
        if not g["events"]:
            problems.append(f"gap {g['id']} names no event")
        for eid in g["events"]:
            if eid not in BY_ID:
                problems.append(f"gap {g['id']} names event {eid}, which does not exist")
            elif g["id"] not in BY_ID[eid].get("absent", []):
                problems.append(f"gap {g['id']} names event {eid}, which does not state the absence")

    order = [e["date"] for e in EVENTS]
    if order != sorted(order, reverse=True):
        problems.append("the chain is not in newest-first order")

    if problems:
        raise SystemExit("tools/sync-record.py: " + "; ".join(problems))


validate()


def long_date(iso):
    y, m, d = iso.split("-")
    return f"{MONTHS[int(m) - 1]} {int(d)}, {y}"


def short_date(iso):
    y, m, d = iso.split("-")
    return f"{MONTHS[int(m) - 1]} {int(d)}"


def key_date(iso):
    y, m, d = iso.split("-")
    return MONTHS[int(m) - 1][:3].upper() + " " + str(int(d)), y


def doc_link(d, text=None):
    """A document as a link where the site holds it, as plain text where it does not."""
    label = text or d["name"]
    if not d["file"]:
        return label
    return (f'<a href="/{d["file"]}" target="_blank" rel="noopener" '
            f'data-cite="{d["cite"]}">{label}</a>')


def render_event(e):
    day, year = key_date(e["date"])
    out = [f'      <section class="event" id="{e["id"]}">']
    key = [f'<b>{day}</b><span class="yr">{year}</span>']
    if e.get("part"):
        key.append(f'<span class="pt">{e["part"]}</span>')
    key.append(f'<span class="kd">{e["kind"].capitalize()}</span>')
    out.append('        <div class="ekey">' + "".join(key) + "</div>")
    out.append('        <div class="ebody">')
    out.append(f'          <p class="ewhat">{e["what"]}</p>')

    if e.get("changed"):
        out.append('          <p class="elabel">What changed</p>')
        out.append('          <ul class="elist">')
        for text, href, label in e["changed"]:
            where = f' <a class="w" href="{href}">{label}</a>' if href else ""
            out.append(f"            <li>{text}{where}</li>")
        out.append("          </ul>")

    if e.get("said"):
        s = e["said"]
        out.append('          <details class="esaid">')
        out.append("            <summary>Who said what</summary>")
        out.append(f'            <p class="ebasis">{s["basis"]}</p>')
        out.append('            <ul class="elist">')
        for line in s["lines"]:
            out.append(f"              <li>{line}</li>")
        out.append("            </ul>")
        out.append("          </details>")

    attached = e.get("attached", [])
    absent = e.get("absent", [])
    if attached or absent:
        out.append('          <p class="elabel">Attached</p>')
        out.append('          <ul class="elist">')
        for slug in attached:
            d = BY_SLUG[slug]
            out.append(f'            <li>{doc_link(d)}. {d["notes"]}. '
                       f'<a class="w" href="#doc-{slug}">In the register</a></li>')
        for gid in absent:
            g = BY_GAP[gid]
            out.append(f'            <li class="none">{g["at_event"]} '
                       f'<a class="w" href="#{gid}">In the gaps register</a></li>')
        out.append("          </ul>")

    if e.get("deeper"):
        out.append('          <p class="elabel">The account in full</p>')
        out.append('          <ul class="elist">')
        for href, label in e["deeper"]:
            out.append(f'            <li><a href="{href}">{label}</a></li>')
        out.append("          </ul>")

    out.append("        </div>")
    out.append("      </section>")
    return "\n".join(out)


def render_chain():
    body = "\n".join(render_event(e) for e in EVENTS)
    return (
        '    <section>\n'
        '      <p class="seclabel">The chain</p>\n'
        f'      <p class="chainnote">{CHAIN_NOTE}</p>\n'
        f"{body}\n"
        "    </section>"
    )


def render_register():
    rows = []
    for d in DOCUMENTS:
        # The file name, so a reader can match a row to what they downloaded. A
        # document the site does not publish has none; its Notes cell says so.
        fn = f'<span class="fn">{os.path.basename(d["file"])}</span>' if d["file"] else ""
        if d["status"] == "current":
            status = '<span class="mark blue">Current</span>'
        elif d["status"] == "superseded":
            s = BY_SLUG[d["superseded_by"]]
            status = ('<span class="mark gray">Superseded</span>'
                      f'<span class="sup">by the {s["name"].lower()}, '
                      f'<a href="#doc-{s["slug"]}">{long_date(s["date"])}</a></span>')
        else:
            status = '<span class="mark gray">Record</span>'
        rows.append(
            f'          <tr id="doc-{d["slug"]}">\n'
            f'            <td>{doc_link(d)}{fn}</td>\n'
            f'            <td><a href="#{d["event"]}">{long_date(d["date"])}</a></td>\n'
            f'            <td>{d["what"]}</td>\n'
            f"            <td>{status}</td>\n"
            f'            <td>{d["notes"]}</td>\n'
            "          </tr>"
        )
    return (
        '    <section id="documents">\n'
        '      <p class="seclabel">Document register</p>\n'
        f'      <p class="regnote">{REGISTER_NOTE}</p>\n'
        '      <div class="tscroll">\n'
        '      <table class="data reg">\n'
        "        <thead><tr><th>Document</th><th>Date</th><th>What it is</th>"
        "<th>Status</th><th>Notes</th></tr></thead>\n"
        "        <tbody>\n" + "\n".join(rows) + "\n"
        "        </tbody>\n"
        "      </table>\n"
        "      </div>\n"
        "    </section>"
    )


def render_gaps():
    rows = []
    for g in GAPS:
        links = [f'<a href="#{eid}">{short_date(BY_ID[eid]["date"])}</a>' for eid in g["events"]]
        if len(links) > 1:
            where = ", ".join(links[:-1]) + " and " + links[-1]
        else:
            where = links[0]
        where += ", " + BY_ID[g["events"][-1]]["date"][:4]
        rows.append(
            f'          <tr id="{g["id"]}">\n'
            f'            <td>{g["name"]}</td>\n'
            f'            <td>{g["means"]}</td>\n'
            f"            <td>{where}</td>\n"
            '            <td><span class="mark gray">Absent</span></td>\n'
            "          </tr>"
        )
    return (
        '    <section id="gaps">\n'
        '      <p class="seclabel">Documents this site does not hold</p>\n'
        f'      <p class="regnote">{GAPS_NOTE}</p>\n'
        '      <div class="tscroll">\n'
        '      <table class="data">\n'
        "        <thead><tr><th>Document</th><th>What its absence means</th>"
        "<th>The event it belongs to</th><th>Status</th></tr></thead>\n"
        "        <tbody>\n" + "\n".join(rows) + "\n"
        "        </tbody>\n"
        "      </table>\n"
        "      </div>\n"
        "    </section>"
    )


BLOCKS = [
    ("/* record: generated by tools/sync-record.py, do not hand-edit */", "/* /record */", CSS),
    ("<!-- record chain: generated by tools/sync-record.py, do not hand-edit -->",
     "<!-- /record chain -->", None),
    ("<!-- record register: generated by tools/sync-record.py, do not hand-edit -->",
     "<!-- /record register -->", None),
    ("<!-- record gaps: generated by tools/sync-record.py, do not hand-edit -->",
     "<!-- /record gaps -->", None),
]


def render(src):
    """Return record.html with all four generated regions rewritten."""
    bodies = [CSS, render_chain(), render_register(), render_gaps()]
    for (open_mark, close_mark, _), body in zip(BLOCKS, bodies):
        pattern = re.compile(re.escape(open_mark) + r".*?" + re.escape(close_mark), re.S)
        if not pattern.search(src):
            raise SystemExit(f"tools/sync-record.py: record.html has no {open_mark} block")
        if open_mark.startswith("/*"):
            replacement = body
        else:
            replacement = open_mark + "\n" + body + "\n" + close_mark
        src = pattern.sub(lambda _: replacement, src, count=1)
    return src


def stale():
    """True when record.html no longer matches the data here."""
    src = open(PAGE).read()
    return render(src) != src


def main():
    check = "--check" in sys.argv
    src = open(PAGE).read()
    new = render(src)
    if new == src:
        print("in sync     record.html")
        print("\n%d events, %d documents, %d gaps." % (len(EVENTS), len(DOCUMENTS), len(GAPS)))
        return 0
    if check:
        print("STALE       record.html")
        print("\nrecord.html is stale. Run without --check to fix.")
        return 1
    open(PAGE, "w").write(new)
    print("updated     record.html")
    print("\n%d events, %d documents, %d gaps." % (len(EVENTS), len(DOCUMENTS), len(GAPS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
