#!/usr/bin/env python3
"""Keep the provenance block identical and current across every page in docs/.

Two things a reader needs and the site did not have:

1. The document chain. Four successive documents govern this subject. Each
   supersedes the one before it. A reader looking at a number on any page
   should be able to walk back and see where it came from and what changed at
   each step, without that history sprawling across the page.

   The chain is stated once, in the register at record.html#documents, whose
   data lives in tools/sync-record.py and is read from there by this script.
   The register holds each document's identity, date, status, and download; the
   block at the foot of a page names the current document, says what it changed,
   and links the register. It used to restate all four documents with their own
   download links, which put the same description of the same document on eight
   pages in different words, and that is the one document-link duplication on
   the site that serves no citation.

2. A per-page revision log. What was changed on this page, and when. Only
   index.html had one, buried in its footer.

Both live in a single collapsed <details> block at the foot of every page:
zipped up by default, opened when a reader wants it.

CHAIN is identical on every page. REVISIONS is per page, newest first.

Every content page carries the block. The seven pages restored from the
pre-redesign site hold it before their sitefoot, with the block's styles
injected into each page's own stylesheet; the seven pages built in the July
27 redesign idiom hold it at the end of main, with the styles in the shared
style.css. Redirect stubs are retired addresses, not destinations, and
carry no block.

Usage:
    python3 tools/sync-provenance.py           # write into every page
    python3 tools/sync-provenance.py --check   # exit 1 if any page is stale
"""
import glob
import importlib.util
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import partlib
PART = partlib.current_part()
DOCS = partlib.docs_dir(PART)

# The document chain lives in the register, in tools/sync-record.py, which is
# where record.html reads it from as well. This block used to carry its own copy
# of every document's date, name, and file, which is two homes for one fact and
# the drift pattern the register exists to end. What stays here is the one thing
# the register does not hold: what the current document changed, which is the
# chain narrative rather than the document's identity.
_spec = importlib.util.spec_from_file_location(
    "syncrecord", os.path.join(ROOT, "tools", "sync-record.py"))
syncrecord = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(syncrecord)

CHAIN = [d for d in syncrecord.DOCUMENTS if d.get("chain")]
partlib.load_data(PART, "sync-provenance", globals())

CSS = """  .prov{margin:26px 0 0; border:1px solid var(--border-strong); border-radius:12px; background:var(--surface); overflow:hidden;}
  .prov>summary{list-style:none; cursor:pointer; padding:13px 16px; display:flex; align-items:center; gap:10px; font-size:13.5px; color:var(--text-muted); background:var(--surface-2);}
  .prov>summary::-webkit-details-marker{display:none;}
  .prov>summary:hover{color:var(--text);}
  .prov .provsum{font-weight:650;}
  .prov .provchev{margin-left:auto; font-size:11px; transition:transform .15s;}
  .prov[open] .provchev{transform:rotate(90deg);}
  .provbody{padding:4px 16px 18px;}
  .provsec{margin-top:16px;}
  .provk{font-size:11px; font-weight:700; letter-spacing:.09em; text-transform:uppercase; color:var(--accent); margin:0 0 10px;}
  .provsec .cd{font-size:12px; font-family:var(--mono); color:var(--text-faint); margin:0;}
  .provsec .cn{font-size:14.5px; font-weight:650; color:var(--text); margin:1px 0 0;}
  .provsec .cw{font-size:13.5px; color:var(--text-muted); line-height:1.55; margin:6px 0 0;}
  .provsec .curflag{display:inline-block; font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; color:var(--agree); background:var(--agree-bg); border:1px solid var(--agree-border); border-radius:20px; padding:1px 8px; margin-left:7px; vertical-align:1px;}
  .revs{list-style:none; margin:0; padding:0;}
  .revs li{font-size:13.5px; color:var(--text-muted); line-height:1.55; padding:8px 0; border-top:1px solid var(--border);}
  .revs li:first-child{border-top:none; padding-top:0;}
  .revs b{color:var(--text); font-weight:650;}
"""

MARK = "<!-- provenance: generated by tools/sync-provenance.py, do not hand-edit -->"
BLOCK_RE = re.compile(re.escape(MARK) + r".*?" + re.escape("<!-- /provenance -->"), re.S)
CSS_MARK = "/* provenance block */"
CSS_RE = re.compile(re.escape(CSS_MARK) + r".*?" + re.escape("/* /provenance block */"), re.S)


WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
         7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build(page):
    cur = next(c for c in CHAIN if c["status"] == "current")
    superseded = len(CHAIN) - 1
    chain = (
        '          <p class="cd">{date}</p>\n'
        '          <p class="cn"><a href="{file}" target="_blank" rel="noopener">{name}</a>'
        '<span class="curflag">Current state of truth</span></p>\n'
        '          <p class="cw">{what}</p>\n'
        '          <p class="cw">This document supersedes {n} earlier ones. Each of them, what it '
        'is, what superseded it and when, and a download, is in the register at '
        '<a href="record.html#documents">Meetings and filings</a>.</p>'
    ).format(date=syncrecord.long_date(cur["date"]), file="/" + cur["file"], name=esc(cur["name"]),
             what=esc(CHANGED[cur["slug"]]), n=WORDS.get(superseded, superseded))

    revs = REVISIONS.get(page)
    if revs:
        items = "\n".join(
            f'          <li><b>{d}</b> {esc(t)}</li>' for d, t in revs
        )
        revblock = (
            '        <div class="provsec">\n'
            '          <p class="provk">Revisions to this page</p>\n'
            '          <ul class="revs">\n' + items + "\n"
            "          </ul>\n"
            "        </div>\n"
        )
    else:
        revblock = ""

    return (
        f"{MARK}\n"
        '      <details class="prov">\n'
        '        <summary><span class="provsum">Provenance: the source document and this page&rsquo;s revisions</span><span class="provchev">&#9656;</span></summary>\n'
        '        <div class="provbody">\n'
        '        <div class="provsec">\n'
        '          <p class="provk">The document this page is read from</p>\n'
        + chain + "\n"
        "        </div>\n"
        + revblock +
        "        </div>\n"
        "      </details>\n"
        "      <!-- /provenance -->"
    )


def main():
    check = "--check" in sys.argv
    changed, ok, stubs, missing = [], [], [], []

    for path in sorted(glob.glob(os.path.join(DOCS, "*.html"))):
        name = os.path.basename(path)
        page = name[:-5]
        src = open(path).read()
        if 'http-equiv="refresh"' in src:
            stubs.append(name)
            continue

        new = src
        block = build(page)
        anchor = '<div class="sitefoot">'
        if anchor in src:
            # A restored page: the block sits before the sitefoot, and its
            # styles are injected into the page's own stylesheet.
            css_block = CSS_MARK + "\n" + CSS + "  " + "/* /provenance block */"
            if CSS_RE.search(new):
                new = CSS_RE.sub(lambda _: css_block, new, count=1)
            else:
                new = new.replace("</style>\n<style id=\"navpass\">", css_block + "\n</style>\n<style id=\"navpass\">", 1)
            if BLOCK_RE.search(new):
                new = BLOCK_RE.sub(lambda _: block, new, count=1)
            else:
                new = new.replace(anchor, block + "\n      " + anchor, 1)
        elif "</main>" in src:
            # A redesign-idiom page: the block closes main, and the shared
            # style.css carries the .prov rules.
            if BLOCK_RE.search(new):
                new = BLOCK_RE.sub(lambda _: block, new, count=1)
            else:
                new = new.replace("</main>", "  " + block + "\n</main>", 1)
        else:
            missing.append(name)
            continue

        if new == src:
            ok.append(name)
        elif check:
            changed.append(name)
        else:
            open(path, "w").write(new)
            changed.append(name)

    for n in changed:
        print(("STALE       " if check else "updated     ") + n)
    for n in ok:
        print("in sync     " + n)
    for n in stubs:
        print("stub        " + n)
    for n in missing:
        print("NO ANCHOR   " + n)

    if missing:
        print("\n%d page(s) with no place for the block." % len(missing))
        return 1
    if check and changed:
        print("\n%d page(s) stale. Run without --check to fix." % len(changed))
        return 1
    print("\n%d page(s), provenance identical." % (len(changed) + len(ok)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
